version: "3.8"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      # target: production
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: always
    networks:
      - node-postgres
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: DockerfileDB
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./database:/usr/app/database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
networks:
  node-postgres:
    driver: bridge
