version: "3.9"

services:
  node-app:
    image: aleksandrosn/nodejs2021q4-service:deploy-node
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - type: volume
        source: node_app_logs
        target: /logs
      - type: bind
        source: ./src
        target: /src
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: always
    networks:
      - node-postgres
    depends_on:
      - postgres
    command: npm run start:dev
  postgres:
    image: aleksandrosn/nodejs2021q4-service:deploy-postgres
    container_name: postgres
    build:
      context: .
      dockerfile: DockerfileDB
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - type: volume
        source: postgresDB
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - node-postgres
networks:
  node-postgres:
    driver: bridge
volumes:
  postgresDB:
  node_app_logs:
