version: "3.9"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - type: bind
        source: ./logs
        target: /logs
      - type: bind
        source: ./src
        target: /src
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: always
    networks:
      - node-postgres
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: DockerfileDB
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - type: volume
        source: postgreDB
        target: /database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - node-postgres
networks:
  node-postgres:
    driver: bridge
volumes:
  postgreDB:
